---
sidebar: sidebar
permalink: hu_ol_63.html
keywords: host utilities, oracle, linux, 6.3, netapp, ontap
summary: Describes how to use Oracle Linux 6.3 with ONTAP
---

= Using Oracle Linux 6.3 with NetApp ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Installing the Linux Unified Host Utilities

include::_include/hu/reuse_hu_installing_luhu_without32.adoc[]

== SAN Toolkit

include::_include/hu/reuse_hu_san_toolkit.adoc[]

== SAN Booting

.Before you begin
If you decide to use SAN booting, it must be supported by your configuration. You can use the https://mysupport.netapp.com/matrix/imt.jsp?components=63560;61723;62441;65621;61722;62440;&solution=1&isHWU&src=IMT[NetApp Interoperability Matrix Tool^] to verify that your OS, HBA, HBA firmware and the HBA boot BIOS, and ONTAP version are supported.

include::_include/hu/reuse_hu_san_booting_steps.adoc[]

== Multipathing

For Oracle Linux 6.3 the /etc/multipath.conf file must exist, but you do not need to make specific changes to the file. Oracle Linux 6.3 is compiled with all settings required to recognize and correctly manage ONTAP LUNs.
include::_include/hu/reuse_hu_enable_alua_steps_ol.adoc[]
include::_include/hu/reuse_hu_asa_confiuration.adoc[]
include::_include/hu/reuse_hu_non_asa_configuration.adoc[]


----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:26:37 sdje 8:384   active ready running
| |- 0:0:25:37 sdik 135:64  active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:18:37 sdda 70:128  active ready running
  |- 0:0:19:37 sddu 71:192  active ready running
----

include::_include/hu/reuse_hu_asa_configuration_note.adoc[]

== Recommended Settings

The Oracle Linux 6.3 OS is compiled to recognize ONTAP LUNs and automatically set all configuration parameters correctly.

include::_include/hu/reuse_hu_recommended_settings_ol6.adoc[]


[cols=2*,options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | "infinity"
| failback | immediate
| fast_io_fail_tmo | 5
| features | "3 queue_if_no_path pg_init_retries 50"
| flush_on_last_del | "yes"
| hardware_handler | "0"
| path_checker | "tur"
| path_grouping_policy | "group_by_prio"
| path_selector | "round-robin 0"
| polling_interval | 5
| prio | "ontap"
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | "uniform"
| user_friendly_names | no
| vendor | NETAPP
|===

.Example

The following example shows how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `detect_prio` that are not compatible with ONTAP LUNs.
If they cannot be removed because of other SAN arrays still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

== Known Problems and Limitations

[cols=4*,options="header"]
|===
| NetApp Bug ID
| Title
| Description
| Bugzilla ID
| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=713555[713555^] | QLogic adapter resets are seen on OL6.4 and OL5.9 with UEK2 on controller faults such as takeover/giveback, and reboot | QLogic adapter resets are seen on OL6.4 hosts with UEK2 (kernel-uek-2.6.39-400.17.1.el6uek) or OL5.9 hosts with UEK2 (kernel-uek-2.6.39-400.17.1.el5uek) when controller faults happen (such as takeover, giveback, and reboots).

 These resets are intermittent. When these adapter resets happen, a prolonged I/O
 outage (sometimes, more than 10 minutes) might occur until the adapter resets
 succeed and the paths' status are updated by dm-multipath.

 In /var/log/messages, messages similar to the following are seen when this bug
 is hit:

 kernel: qla2xxx [0000:11:00.0]-8018:0: ADAPTER RESET ISSUED nexus=0:2:13.

 This is observed with the kernel version:
 On OL6.4: kernel-uek-2.6.39-400.17.1.el6uek
 On OL5.9: kernel-uek-2.6.39-400.17.1.el5uek
| link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=13999[13999^]

|===

include::_include/hu/reuse_hu_ol_issues_note.adoc[]

== Release Notes

include::_include/hu/reuse_hu_release_notes.adoc[]
