---
sidebar: sidebar
permalink: nvme_esxi_7.html
keywords: nvme, esxi, ontap
summary: Describes how to configure NVMe/FC for ESXi 7.0 with ONTAP
---

= NVMe/FC Host Configuration for ESXi 7.0 with ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

== Supportability

NVME/FC is supported on ONTAP 9.7 or later for ESXi 7.0.

ESXi initiator host can run both NVMe/FC & FC-SCSI traffic through the same adapter ports. See the link:https://hwu.netapp.com/Home/Index[Hardware Universe] for a list of supported FC adapters and controllers.

For the most current list of supported configurations & versions, see the link:https://mysupport.netapp.com/matrix/[NetApp Interoperability Matrix].

==	Known limitations

None.

==	Enabling NVMe/FC with ANA

.	Copy the driver to /tmp or any other folder and execute the following command.
+
----
# esxcli software vib install -d <offlinebundle> --no-sig-check
[root@interop-57-131:~] esxcli software vib install -d /tmp/t/Emulex-FCoE-FC-lpfc-12.4.224.0-offline-bundle-13621872.zip --no-sig-check
Installation Result
   Message: The update completed successfully, but the system needs to be rebooted for the changes to be effective.
   Reboot Required: true
   VIBs Installed: EMU_bootbank_lpfc_12.4.224.0-1OEM.688.0.0.13621872
   VIBs Removed: EMU_bootbank_lpfc_12.4.211.6-1OEM.688.0.0.13621872
   VIBs Skipped:
----

.	Install the elxmgmt tool for upgrading the HBA firmware.
+
----
# esxcli software vib install -d <elxmgmt-bundle> --no-sig-check
[root@interop-57-131:~] esxcli software vib install -d /tmp/t//Emulex-elxmgmt-6.8.7-12.4.211.7.zip --no-sig-check
Installation Result
   Message: The update completed successfully, but the system needs to be rebooted for the changes to be effective.
   Reboot Required: true
   VIBs Installed: EMU_bootbank_emu-esx-elxmgmt_12.4.211.7-01
   VIBs Removed:
   VIBs Skipped:
…
----

.	Install the firmware on Broadcom HBA:
+
----
# esxcli elxmgmt listhbas
Manageable HBA List
Port WWN       : 10:00:00:90:fa:e0:ec:8e
Node WWN       : 20:00:00:90:fa:e0:ec:8e
Fabric Name    : 10:00:88:94:71:1a:1c:00
Flags          : 8000e300
Host Name      : interop-57-131
Mfg            : Emulex Corporation
Serial No.     : FC64915246
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
Port Type      : FC
Model          : LPe32002-M2
----

. Set the following parameter to 0 for improved interoperability.
+
`# esxcfg-advcfg -s 0 /Misc/HppManageDegradedPaths`

. Reboot the host.

. Verify that the parameter is disabled.
+
----
# esxcfg-advcfg -g /Misc/HppManageDegradedPaths
Value of HppManageDegradedPaths is 0
----

==	Configuring the Broadcom FC adapter for NVMe/FC

.	Enable FC4 types:
+
`# esxcli system module parameters set -m lpfc -p lpfc_enable_fc4_type=3"`

.	Verify that you are using the supported adapter. For the most current list of supported adapters see the NetApp Interoperability Matrix.
+
----
# esxcli storage san fc list
 Adapter: vmhba3
   Port ID: 010600
   Node Name: 20:00:00:90:fa:e0:ec:8e
   Port Name: 10:00:00:90:fa:e0:ec:8e
   Speed: 32 Gbps
   Port Type: NPort
   Port State: ONLINE
   Model Description: Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
   Hardware Version: 0000000c
   OptionROM Version: 12.4.217.2
   Firmware Version: 12.4.217.2
   Driver Name: lpfc
   DriverVersion: 12.4.224.0

   Adapter: vmhba4
   Port ID: 010F00
   Node Name: 20:00:00:90:fa:e0:ec:8f
   Port Name: 10:00:00:90:fa:e0:ec:8f
   Speed: 32 Gbps
   Port Type: NPort
   Port State: ONLINE
   Model Description: Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
   Hardware Version: 0000000c
   OptionROM Version: 12.4.217.2
   Firmware Version: 12.4.217.2
   Driver Name: lpfc
   DriverVersion: 12.4.224.0
----

.	Verify that the target controllers are discovered.
+
----
# esxcli nvme controller list

Name                                                                                                                             Controller Number  Adapter  Transport Type  Is Online
-------------------------------------------------------------------------------------------------------------------------------  -----------------  -------  --------------  ---------
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_01#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                259  vmhba32  FC                  false
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_09#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                263  vmhba32  FC                  false
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_11#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                267  vmhba32  FC                  false
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_10#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                265  vmhba32  FC                  false
nqn.1992-08.com.netapp:sn.e7f89c2c245d11e9975300a098dfce55:subsystem.interop_57_vm_02#vmhba32#204900a098dfe3d1:204a00a098dfe3d1                261  vmhba32  FC                  false
----

. For Broadcom Emulex LPe3200x, set the following parameter to detect the namespaces, then reboot the system. You do not need to set this parameter for the Broadcom LPe3500x.
+
`# esxcli system module parameters set -m lpfc -p lpfc_enable_fc4_type=3`

==	Validating NVMe/FC

.	Verify the namespaces have been created.
UUID devices represent namespaces.
+
----
#esxcfg-mpath -b
uuid.0d12b7cd97344be8a53b7913f8f72f04 : NVMe Fibre Channel Disk (uuid.0d12b7cd97344be8a53b7913f8f72f04)
   vmhba65:C0:T9:L30 LUN:30 state:active fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8f WWPN: 10:00:00:90:fa:e0:ec:8f  Target: WWNN: 20:49:00:a0:98:df:e3:d1 WWPN: 20:4d:00:a0:98:df:e3:d1
   vmhba64:C0:T9:L30 LUN:30 state:active fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8e WWPN: 10:00:00:90:fa:e0:ec:8e  Target: WWNN: 20:49:00:a0:98:df:e3:d1 WWPN: 20:4c:00:a0:98:df:e3:d1
   vmhba64:C0:T5:L30 LUN:30 state:standby fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8e WWPN: 10:00:00:90:fa:e0:ec:8e  Target: WWNN: 20:49:00:a0:98:df:e3:d1 WWPN: 20:4a:00:a0:98:df:e3:d1
   vmhba65:C0:T0:L30 LUN:30 state:standby fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8f WWPN: 10:00:00:90:fa:e0:ec:8f  Target: WWNN: 20:49:00:a0:98:df:e3:d1 WWPN: 20:4b:00:a0:98:df:e3:d1

uuid.49de7683950d47c9898f51443d893910 : NVMe Fibre Channel Disk (uuid.49de7683950d47c9898f51443d893910)
   vmhba65:C0:T12:L39 LUN:39 state:active fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8f WWPN: 10:00:00:90:fa:e0:ec:8f  Target: WWNN: 20:3a:00:a0:98:df:e3:d1 WWPN: 20:27:00:a0:98:df:e3:d1
   vmhba65:C0:T13:L39 LUN:39 state:standby fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8f WWPN: 10:00:00:90:fa:e0:ec:8f  Target: WWNN: 20:3a:00:a0:98:df:e3:d1 WWPN: 20:29:00:a0:98:df:e3:d1
   vmhba64:C0:T12:L39 LUN:39 state:active fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8e WWPN: 10:00:00:90:fa:e0:ec:8e  Target: WWNN: 20:3a:00:a0:98:df:e3:d1 WWPN: 20:3b:00:a0:98:df:e3:d1
   vmhba64:C0:T13:L39 LUN:39 state:standby fc Adapter: WWNN: 20:00:00:90:fa:e0:ec:8e WWPN: 10:00:00:90:fa:e0:ec:8e  Target: WWNN: 20:3a:00:a0:98:df:e3:d1 WWPN: 20:28:00:a0:98:df:e3:d1
----

.	Verify the status of the ANA paths.
+
----
esxcli storage hpp path list
fc.20000090fae0ec8f:10000090fae0ec8f-fc.204900a098dfe3d1:204d00a098dfe3d1-uuid.1aa669c5376240a28ae47d8d549586ea
   Runtime Name: vmhba65:C0:T9:L33
   Device: uuid.1aa669c5376240a28ae47d8d549586ea
   Device Display Name: NVMe Fibre Channel Disk (uuid.1aa669c5376240a28ae47d8d549586ea)
   Path State: active

fc.20000090fae0ec8e:10000090fae0ec8e-fc.204900a098dfe3d1:204a00a098dfe3d1-uuid.1aa669c5376240a28ae47d8d549586ea
   Runtime Name: vmhba64:C0:T5:L33
   Device: uuid.1aa669c5376240a28ae47d8d549586ea
   Device Display Name: NVMe Fibre Channel Disk (uuid.1aa669c5376240a28ae47d8d549586ea)
   Path State: standby
----
